FullKeyboard=no
JoyButton-0=@DEVICE_BTN_SOUTH@,A
JoyButton-1=@DEVICE_BTN_WEST@,X
JoyButton-2=@DEVICE_BTN_EAST@,B
JoyButton-3=@DEVICE_BTN_NORTH@,Y
JoyButton-4=@DEVICE_BTN_TL@,L
JoyButton-5=@DEVICE_BTN_TR@,R
JoyButton-6=@DEVICE_BTN_SELECT@,Select
JoyButton-7=@DEVICE_BTN_START@,Start
JoyButton-8=@DEVICE_BTN_MODE@,Menu
JoyButton-9=@DEVICE_BTN_THUMBL@,L3
JoyButton-10=@DEVICE_BTN_THUMBR@,R3
JoyButton-11=@DEVICE_BTN_TL2@,L2
JoyButton-12=@DEVICE_BTN_TR2@,R2
JoyAxis-0=-1,Left
JoyAxis-1=1,Right
JoyAxis-2=-2,Up
JoyAxis-3=2,Down
